import { useState } from 'react';
import { Package, FileText, Code2, Image as ImageIcon, Search, Download, ExternalLink, Filter, MoreVertical } from 'lucide-react';
import DashboardLayout from '../components/layout/DashboardLayout';
import clsx from 'clsx';

export default function Deliverables() {
  const [activeType, setActiveType] = useState('all');

  // Mock deliverables for now as they are usually generated during AI interactions
  const mockDeliverables = [
    { id: '1', name: 'Project Timeline.pdf', type: 'document', project: 'Project Phoenix', date: '2 hours ago', size: '1.2 MB' },
    { id: '2', name: 'LandingPage.tsx', type: 'code', project: 'Crew OS Launch', date: '5 hours ago', size: '14 KB' },
    { id: '3', name: 'Brand_Guidelines.v3', type: 'image', project: 'Marketing Blitz', date: 'Yesterday', size: '8.4 MB' },
    { id: '4', name: 'Database_Schema.sql', type: 'code', project: 'Project Phoenix', date: '2 days ago', size: '42 KB' },
    { id: '5', name: 'Market_Analysis.docx', type: 'document', project: 'Marketing Blitz', date: '3 days ago', size: '2.1 MB' },
  ];

  const types = [
    { id: 'all', label: 'All Files', icon: Package },
    { id: 'document', label: 'Documents', icon: FileText },
    { id: 'code', label: 'Source Code', icon: Code2 },
    { id: 'image', label: 'Visual Assets', icon: ImageIcon },
  ];

  const filtered = mockDeliverables.filter(d => activeType === 'all' || d.type === activeType);

  return (
    <DashboardLayout>
      <div className="p-8 max-w-7xl mx-auto space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-text-primary">Deliverables</h1>
          <p className="text-text-secondary mt-1">Access and manage all artifacts generated by your AI crew.</p>
        </div>

        <div className="flex flex-col md:flex-row gap-6">
          {/* Sidebar Filters */}
          <aside className="w-full md:w-64 shrink-0 space-y-6">
             <nav className="bg-surface rounded-2xl border border-border overflow-hidden">
                {types.map((type) => (
                    <button
                        key={type.id}
                        onClick={() => setActiveType(type.id)}
                        className={clsx(
                            "w-full flex items-center gap-3 px-4 py-3.5 text-sm font-medium transition-all border-l-2",
                            activeType === type.id 
                                ? "bg-primary/5 border-primary text-primary" 
                                : "border-transparent text-text-secondary hover:text-text-primary hover:bg-white/[0.02]"
                        )}
                    >
                        <type.icon className="w-4 h-4" />
                        {type.label}
                    </button>
                ))}
             </nav>

             <div className="glass-panel p-6 rounded-2xl border border-border">
                <h4 className="text-[11px] font-bold text-text-muted uppercase tracking-wider mb-4">Storage Usage</h4>
                <div className="w-full h-1.5 bg-surface-2 rounded-full overflow-hidden">
                    <div className="h-full bg-primary w-[32%]" />
                </div>
                <div className="flex justify-between mt-2">
                    <span className="text-[10px] text-text-muted">1.4 GB used</span>
                    <span className="text-[10px] text-text-muted">5 GB total</span>
                </div>
             </div>
          </aside>

          {/* Deliverables Grid/List */}
          <div className="flex-1 space-y-4">
             <div className="flex items-center gap-4 bg-surface p-2 rounded-2xl border border-border">
                <div className="relative flex-1">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
                    <input 
                        placeholder="Search for artifacts..."
                        className="w-full h-10 bg-transparent pl-12 pr-4 text-sm text-text-primary focus:outline-none"
                    />
                </div>
                <button className="h-10 px-4 flex items-center gap-2 text-sm font-medium text-text-secondary hover:text-text-primary transition-colors">
                    <Filter className="w-4 h-4" /> Filter
                </button>
             </div>

             <div className="grid grid-cols-1 gap-3">
                {filtered.map((item) => (
                    <div key={item.id} className="glass-panel group p-4 rounded-2xl border border-border flex items-center gap-4 hover-card transition-all">
                        <div className={clsx(
                            "w-12 h-12 rounded-xl flex items-center justify-center border",
                            item.type === 'document' ? "bg-blue-500/10 border-blue-500/20 text-blue-500" :
                            item.type === 'image' ? "bg-purple-500/10 border-purple-500/20 text-purple-500" :
                            "bg-amber-500/10 border-amber-500/20 text-amber-500"
                        )}>
                            {item.type === 'document' ? <FileText className="w-5 h-5" /> : 
                             item.type === 'image' ? <ImageIcon className="w-5 h-5" /> : 
                             <Code2 className="w-5 h-5" />}
                        </div>
                        
                        <div className="flex-1 min-w-0">
                            <h4 className="text-sm font-bold text-text-primary truncate">{item.name}</h4>
                            <div className="flex items-center gap-3 mt-1">
                                <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider">{item.project}</span>
                                <span className="text-[10px] text-text-muted">•</span>
                                <span className="text-[10px] text-text-muted italic">{item.size}</span>
                            </div>
                        </div>

                        <div className="text-right shrink-0">
                            <p className="text-[10px] text-text-muted mb-1.5">{item.date}</p>
                            <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                                <button className="p-1.5 rounded-lg bg-surface-2 hover:bg-primary hover:text-white transition-all">
                                    <Download className="w-3.5 h-3.5" />
                                </button>
                                <button className="p-1.5 rounded-lg bg-surface-2 hover:bg-white/10 transition-all">
                                    <MoreVertical className="w-3.5 h-3.5 text-text-muted" />
                                </button>
                            </div>
                        </div>
                    </div>
                ))}
             </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
